server:
  port: 8094

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #47.107.191.93
    url: jdbc:mysql://localhost:3306/blctek?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password:
  application:
    name: user-server

mybatis:
  mapper-locations: mybatis/mapper/*Mapper.xml