spring:
  profiles:
    active: prod

  application:
    name: user-server

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      stat-view-servlet:
        enabled: true
        login-username: mysql
        login-password: mysql

server:
  port: 8097

mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml