spring:
  profiles:
    active: prod #当前激活的application环境配置

  application:
    name: engine-server

server:
  port: 8096

#使用classpath*可以扫描所有的资源路径（包括jar），使用classpath只扫描当前的资源路径
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
