server:
  port: 8091

spring:
  application:
    name: engine-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blctek?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password:

#使用classpath*可以扫描所有的资源路径（包括jar），使用classpath只扫描当前的资源路径
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
